$activeBorderColor = rgb(61E2FF)
$activeShadowColor = rgb(d0b2ff)
$inactiveBorderColor = rgba(4a4a5a99)
$inactiveShadowColor = rgba(22203077)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 8
    gaps_out = 16
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    shadow {
      enabled = true
      range = 16
      render_power = 4
      color = $activeShadowColor
      color_inactive = $inactiveShadowColor
    }
}
