$activeBorderColor = rgb(61E2FF)
$inactiveBorderColor = rgba(4a4a5a99)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 8
    gaps_out = 16
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    shadow {
      enabled = false
    }
}
