return {
  {
    "maxmx03/fluoromachine.nvim",
    config = function()
      local fm = require("fluoromachine")
      fm.setup({
        glow = false,
        theme = "retrowave",
        brightness = 0.02,
        transparent = false,
        overrides = function(c, color)
          return {
            ["@lsp.typemod.variable.readonly.typescript"] = { link = "@variable" },
            ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
            ["@lsp.typemod.variable.readonly"] = { link = "@variable" },
            ["@lsp.typemod.variable.global"] = { link = "@variable" },
            ["@lsp.typemod.property.readonly"] = { link = "@variable" },
            ["@lsp.type.parameter"] = { link = "@variable" },
            ["@variable.parameter"] = { link = "@variable" },
            ["@lsp.typemod.variable.defaultLibrary.typescriptreact"] = { link = "@variable.builtin" },
            ["@tag.builtin.tsx"] = { link = "@tag" },
            ["@tag"] = { link = "Tag" },
            ["LspInlayHint"] = { fg = "#65345A" },
            ["@parameter"] = { link = "@variable" },
            ["@string.documentation.python"] = { link = "@comment" },
            MiniIconsYellow = { fg = c.yellow },
            MiniIconsGreen = { fg = c.green },
            MiniIconsRed = { fg = c.red },
            MiniIconsCyan = { fg = c.cyan },
            MiniIconsPurple = { fg = c.purple },
            MiniIconsOrange = { fg = c.orange },
            MiniIconsGray = { fg = c.comment },
            MiniIconsAzure = { fg = "#61E2FF" },
            MiniIconsBlue = { fg = "#61E2FF" },
            DiffAdd = { fg = c.green, bg = "#23362f" },
            DiffDelete = { fg = c.red, bg = "#3f2630" },
            DiffChange = { fg = c.orange, bg = "#3b3126" },
            DiffText = { fg = c.green, bg = "#2b463c", bold = true },
            diffAdded = { fg = c.green, bold = true },
            diffRemoved = { fg = c.red, bold = true },
            diffChanged = { fg = c.orange, bold = true },
            DiffviewDiffAdd = { fg = c.green, bg = "#23362f" },
            DiffviewDiffDelete = { fg = c.red, bg = "#3f2630" },
            DiffviewDiffChange = { fg = c.orange, bg = "#3b3126" },
            DiffviewDiffText = { fg = c.green, bg = "#2b463c", bold = true },
            DiffviewDiffAddAsDelete = { fg = c.red, bg = "#3f2630" },
            DiffviewDiffDeleteDim = { fg = "#8d6171", bg = "#2a1d24" },
            MiniDiffOverAdd = { fg = "None", bg = "#2a4a36" },
            MiniDiffOverChange = { bg = "#4a3a2a", fg = "#ffb86c" },
            MiniDiffOverDelete = { bg = "#4a2a2a", fg = "#ff8288" },
          }
        end,
        colors = function()
          return {
            fg = "#f8f8f8",
            bg = "#222030",
            alt_bg = "#282836",
            currentline = "#4a4a5a",
            selection = "#4a4a5a",
            comment = "#6A6AB6",
            cyan = "#61E2FF",
            green = "#a2f9d4",
            orange = "#ffaf76",
            pink = "#ff9eff",
            purple = "#d0b2ff",
            red = "#ff8288",
            yellow = "#ffed90",
            cursor_fg = "#57575a",
            cursor_bg = "#e9e9e9",
            sign_add = "#a2f9d4",
            sign_change = "#ffaf76",
            sign_delete = "#ff8288",
            error = "#ff5560",
            warning = "#ffaf76",
            info = "#a0e4ff",
            hint = "#a0e4ff",
            other = "#d0b2ff",
            blankline = "#7f7f95",
            active_blankline = "#6f8f84",
            inlay_hint = "#e49ebd",
            git = {
              add = "#a2f9d4",
              change = "#8fcf9b",
              delete = "#ff8288",
            },
          }
        end,
      })

      vim.cmd.colorscheme("fluoromachine")
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "fluoromachine",
    },
  },
}
